            <footer>
                <ul>
                    <li>&copy;2013 Sugar Sands Beach Weddings</li>
                    <li><a href="index.php?ssbw/view/site_map">Site Map</a></li>
                    <li><a href="index.php?ssbw/view/terms_policies">Terms and Policies</a></li>
                </ul>
            </footer>
            <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
            <script type="text/javascript" src="<? echo base_url('js/slideshow.js'); ?>"></script>
            <script type="text/javascript" src="<? echo base_url('js/gallery.js'); ?>"></script>
            <script type="text/javascript" src="<? echo base_url('js/buttons.js'); ?>"></script>
            <script type="text/javascript" src="<? echo base_url('js/admin_lists.js'); ?>"></script>
        </div> <!-- End Container Div -->
     </body> <!-- End Body Section -->
</html>